biodiversidad_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.Login.as_view(), name='login'),
    url(r'^logout$', views.Logout.as_view(), name='logout'),
    url(r'^especie/(\d+)/$', views.specie_view, name='verEspecie'),
    url(r'^registrar-usuario/$', views.add_user_view, name='addUser'),
    url(r'^actualizar-usuario/$', views.update_user_view, name='updateUser'),
    url(r'^comentar/(?P<species_id>\d+)/$', views.add_comment, name='addComment'),
    url(r'^mis-favoritos$', views.my_favorites_species, name='my-favorites-species'),
    url(r'^eliminar-favorito$', views.delete_favorite, name='delete-favorite')
]

biodiversidad_miso/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('biodiversidad_app.urls_rest', namespace='biodiversidad-rest')),
    url(r'^', include('biodiversidad_app.urls', namespace='biodiversidad')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biodiversidad_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.contrib.auth.models import User


@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Categoría', null=False, blank=False)

    class Meta:
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Species(models.Model):
    fk_category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Categoría', null=False, blank=False)
    name = models.CharField(max_length=150, verbose_name='Nombre', unique=True, null=False, blank=False)
    scientific_name = models.CharField(max_length=150, verbose_name='Nombre científico', unique=True, null=False, blank=False)
    taxonomic_classification = models.CharField(max_length=150, verbose_name='Clasificación taxonómica', null=False, blank=False)
    picture = models.ImageField(upload_to='species-images', verbose_name='Imagen', null=False, blank=False)
    short_description = models.TextField(max_length=150, verbose_name='Descripción corta', null=False, blank=False)
    long_description = models.TextField(max_length=300, verbose_name='Descripción larga', null=False, blank=False)

    class Meta:
        verbose_name = 'Especie'
        verbose_name_plural = 'Especies'

    def __str__(self):
        return self.name

    def to_json(self):
        return {
            "name": self.name,
            "fk_category_name": self.fk_category.name,
            "picture": self.picture.url if self.picture else '',
            "short_description": self.short_description,
            "id": self.id
        }


@python_2_unicode_compatible
class Comment(models.Model):
    fk_species = models.ForeignKey(Species, on_delete=models.CASCADE, verbose_name='Especie', null=False, blank=False)
    email = models.EmailField(max_length=150, verbose_name='Email', null=False, blank=False)
    comment = models.TextField(max_length=1000, verbose_name='Comentario', null=False, blank=False)
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación', editable=False, null=False, blank=False)

    class Meta:
        verbose_name = 'Comentario'
        verbose_name_plural = 'Comentarios'

    def __str__(self):
        return 'Comentario de {0} sobre la especie {1}'.format(self.email, self.fk_species.name)


@python_2_unicode_compatible
class AppUser(models.Model):
    fk_django_user = models.OneToOneField(User, verbose_name='Usuario del sistema', null=False, blank=False)
    picture = models.ImageField(upload_to='user-pictures', verbose_name='Foto', null=True, blank=False)
    city = models.CharField(max_length=100, verbose_name='Ciudad', null=False, blank=False)
    country = models.CharField(max_length=100, verbose_name='Pais', null=False, blank=False)
    interest = models.TextField(max_length=1000, verbose_name='Interés', null=True, blank=True)

    favorites_species = models.ManyToManyField(Species, verbose_name='Especies favoritas', blank=True)

    class Meta:
        verbose_name = 'Usuario de la aplicación'
        verbose_name_plural = 'Usuarios de la aplicación'

    @property
    def first_name(self):
        return self.fk_django_user.first_name

    @property
    def last_name(self):
        return self.fk_django_user.last_name

    @property
    def username(self):
        return self.fk_django_user.username

    def __str__(self):
        return '{0} {1}'.format(self.first_name, self.last_name)

biodiversidad_app/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.contrib.auth.forms import forms
from django.forms import ModelForm
from biodiversidad_app.models import AppUser

class AbstractUserForm(ModelForm):
    first_name = forms.CharField(max_length=User._meta.get_field('first_name').max_length, label='Nombres')
    last_name = forms.CharField(max_length=User._meta.get_field('last_name').max_length, label='Apellidos')
    email = forms.EmailField(label='Correo electrónico')
    city = forms.CharField(max_length=100, label='Ciudad')
    country = forms.CharField(max_length=100, label='País')
    interest = forms.CharField(widget=forms.Textarea(), max_length=1000, label='Interés')
    password = forms.CharField(widget=forms.PasswordInput(), label='Contraseña')
    password2 = forms.CharField(widget=forms.PasswordInput(), label='Confirma tu contraseña')

    def clean_password2(self):
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']
        if password != password2:
            raise forms.ValidationError('Las claves no coinciden.')
        return password2


class UserForm(AbstractUserForm):
    picture = forms.ImageField(label='Imagen de perfil')
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'city', 'country', 'interest', 'password', 'password2', 'picture']

    def clean_username(self):

        username = self.cleaned_data['username']
        if User.objects.filter(username=username):
            raise forms.ValidationError('Nombre de usuario ya registrado. ')
        return username

    def clean_email(self):

        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError('Ya existe un email igual registrado. ')
        return email


class UserFormUpdate(AbstractUserForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'city', 'country', 'interest', 'password', 'password2']

biodiversidad_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.db.transaction import atomic
from django.template.loader import get_template
from biodiversidad_app.models import Species, Category, Comment, AppUser
from biodiversidad_app.forms import UserForm, UserFormUpdate
from biodiversidad_app.utils import send_html_mail


def index(request):
    category_list = Category.objects.all()
    form = UserForm()
    context = {'category_list': category_list, 'form': form}
    return render(request, 'biodiversidad_app/index.html', context)


class Login(View):
    def post(self, request):
        if request.user.is_authenticated:
            return redirect(reverse('biodiversidad:index'))

        username = request.POST.get('email', '')
        password = request.POST.get('password', '')
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
        else:
            messages.add_message(request, messages.WARNING, 'Por favor verifique el nombre de usuario y la contraseña')
        return redirect(reverse('biodiversidad:index'))


class Logout(View):
    def get(self, request):
        logout(request)
        return redirect(reverse('biodiversidad:index'))


def specie_view(request, species_id=None):
    species = Species.objects.filter(id=species_id).first()
    if species:
        comments = Comment.objects.filter(fk_species=species.id)
        context = {
            'specie': species,
            'comments': comments,
            'form': UserForm()
        }
        return render(request, 'biodiversidad_app/verEspecie.html', context)
    else:
        messages.add_message(request, messages.WARNING, 'Lo sentimos, no encontramos la especie que estabas buscando')
        return redirect(reverse('biodiversidad:index'))


@atomic
def add_user_view(request):
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            email = cleaned_data.get('email')
            first_name = cleaned_data.get('first_name')
            last_name = cleaned_data.get('last_name')
            password = cleaned_data.get('password')
            city = cleaned_data.get('city')
            country = cleaned_data.get('country')
            picture = cleaned_data.get('picture')
            interest = cleaned_data.get('interest')

            user_model = User.objects.create_user(
                username=email,
                password=password,
                first_name=first_name,
                last_name=last_name,
                email=email
            )
            user_model.save()

            app_user_model = AppUser(fk_django_user=user_model, picture=picture, city=city, country=country, interest=interest)
            app_user_model.save()
            template = get_template('biodiversidad_app/emails/welcome.html')
            content = template.render({
                'name': '{0} {1}'.format(first_name, last_name)
            })
            send_html_mail('Bienvenido a Biodiversidad G2', content, [email])

            login(request, user_model)

            messages.add_message(request, messages.SUCCESS, 'El registro se realizó exitosamente')
            return HttpResponseRedirect(reverse('biodiversidad:index'))
    else:
        form = UserForm()
    context = {
        'form': form
    }
    return render(request, 'biodiversidad_app/_forms/user_registration.html', context)


@atomic
def update_user_view(request):
    if request.method == 'POST':
        form = UserFormUpdate(request.POST, request.FILES)

        if form.is_valid():
            cleaned_data = form.cleaned_data
            email = cleaned_data.get('email')
            first_name = cleaned_data.get('first_name')
            last_name = cleaned_data.get('last_name')
            password = cleaned_data.get('password')
            city = cleaned_data.get('city')
            country = cleaned_data.get('country')
            interest = cleaned_data.get('interest')

            user_model = User.objects.get(username=request.user.username, password=request.user.password)
            user_model.first_name = first_name
            user_model.last_name = last_name
            user_model.email = email

            if password != '':
                user_model.set_password(password)

            user_model.save()

            app_user_model = AppUser.objects.get(fk_django_user=user_model)
            app_user_model.city = city
            app_user_model.country = country
            app_user_model.interest = interest

            app_user_model.save()
            messages.add_message(request, messages.SUCCESS, 'Sus cambios fueron guardados exitosamente')
            return redirect(reverse('biodiversidad:index'))
    else:
        form = UserFormUpdate()
        user_model = User.objects.get(username=request.user.username, password=request.user.password)
        app_user_model = AppUser.objects.get(fk_django_user=user_model)
        form.fields["first_name"].initial = request.user.first_name
        form.fields["last_name"].initial = request.user.last_name
        form.fields["email"].initial = request.user.email
        form.fields["city"].initial = app_user_model.city
        form.fields["country"].initial = app_user_model.country
        form.fields["interest"].initial = app_user_model.interest
    context = {
        'form': form
    }
    return render(request, 'biodiversidad_app/_forms/user.html', context)


@atomic
def add_comment(request, species_id):
    try:
        if request.method == 'POST':
            email = request.POST.get('email', '')
            comentario = request.POST.get('comentario', '')
            specie_model = Species.objects.get(id=species_id)
            comment_model = Comment(fk_species=specie_model, email=email, comment=comentario)
            comment_model.save()
            return redirect(reverse('biodiversidad:index'))
    except:
        return redirect(reverse('biodiversidad:index'))


def my_favorites_species(request):
    if request.user.is_authenticated:
        user = AppUser.objects.filter(fk_django_user_id=request.user.id).first()
        if user:
            species_list = user.favorites_species.all()
            if species_list.count() > 0:
                return render(request, 'biodiversidad_app/my_favorites.html', {'species_list': species_list, 'form': UserForm()})
            else:
                messages.add_message(request, messages.WARNING, 'Aun no has agregado especies favoritas')
    return redirect(reverse('biodiversidad:index'))


@atomic
def delete_favorite(request):
    if request.user.is_authenticated:
        user = AppUser.objects.filter(fk_django_user_id=request.user.id).first()
        if user and request.method == 'POST':
            species_id = request.POST.get('species_id', 0)
            species = Species.objects.filter(id=species_id).first()
            if species:
                user.favorites_species.remove(species)
                messages.add_message(request, messages.SUCCESS, 'La especie favorita se elminó exitosamente')
                return redirect(reverse('biodiversidad:my-favorites-species'))
    return redirect(reverse('biodiversidad:index'))

biodiversidad_app/templates/biodiversidad_app/_elements/_modal-login.html
<div id="login-modal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="text-center modal-title">Ingresar</h3>
            </div>
            <div class="modal-body">
                {% include 'biodiversidad_app/_forms/_login-form.html' %}
            </div>
        </div>
    </div>
</div>

biodiversidad_app/templates/biodiversidad_app/_elements/_modal-sign-up.html
<div id="sign-up-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="text-center modal-title">Registro</h3>
            </div>
            <div class="modal-body">
                {% include 'biodiversidad_app/_forms/user_registration.html' %}
            </div>
        </div>
    </div>
</div>

biodiversidad_app/templates/biodiversidad_app/_elements/_specie-detail.html
<div class="panel panel-default">
    <div class="panel-heading" style="height: 40px;">
        <button type="button" class="close closeDetalle" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="panel-body">
        <img src="{{ specie.picture.url }}" class="img-responsive center-block col-lg-6 col-sm-12 col-md-6"
             style="max-height: 250px" alt="Imagen de la especie">
        <ul class="list-group col-lg-6 col-sm-12 col-md-6">
            <li class="list-group-item text-center"><strong>Nombre de la especie:</strong> <br>{{ specie.name }}</li>
            <li class="list-group-item text-center"><strong>Clasificación Taxonómica:</strong>
                <br>{{ specie.taxonomic_classification }}</li>
            <li class="list-group-item text-center"><strong>Nombre Científico:</strong> <br>{{ specie.scientific_name }}
            </li>
            <li class="list-group-item text-center"><strong>Categoría:</strong> <br>{{ specie.fk_category.name }}</li>
        </ul>

        <div class="species-detail-description col-lg-12 col-sm-12 col-md-12">
            <p><strong>Descripción:</strong> <br>{{ specie.long_description }}</p>
        </div>
        <br>
        <div class="col-lg-12 col-sm-12 col-md-12">
            <h2>Comentarios</h2>
            <form method="post" action="{% url 'biodiversidad:addComment' species_id=specie.id %}">
                {% csrf_token %}
                <div class="col-lg-12 col-sm-12 col-md-12">
                    {% if not user.is_authenticated %}
                        <input type="email" name="email" class="form-control" id="kontakt-email"
                               placeholder="Ingresa tu Correo">
                    {% else %}
                        <textarea name="email" type="email" class="form-control" id="kontakt-email"
                                  style="display:none">{{ user.email }}</textarea>
                    {% endif %}
                    <textarea name="comentario" type="comentario" class="form-control" id="kontakt-nachricht" rows="5"
                              placeholder="Ingresa tu Comentario"></textarea>
                    <input type="submit" value="Enviar" class="btn btn-primary">
                </div>
            </form>

            <ul>
                {% for comment in comments %}
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <li>
                            <p>
                                {{ comment.comment }}<br>
                                Por: {{ comment.email }}<br>
                                Fecha:{{ comment.date_created }}<br>
                            </p>
                        </li>
                    </div>
                {% endfor %}
            </ul>
        </div>

    </div>
</div>

biodiversidad_app/templates/biodiversidad_app/_elements/_species-preview.html
<div class="panel panel-default">
    <div class="panel-heading" style="position:relative;">
        <h3 class="text-center">{{ species.fk_category.name }}</h3>

    </div>
    <div class="panel-body">
        <div style="height: 305px;">
            <img src="{{ species.picture.url }}" class="img-responsive center-block" style="max-height: 300px;" alt="Imagen de la especie">
        </div>
        <h4 class="text-center">{{ species.name }}</h4>
        <div class="species-preview-description">
             {{ species.short_description|linebreaks }}
        </div>
        <form method="post" action="{% url 'biodiversidad:delete-favorite' %}">
            {% csrf_token %}
            <input type="hidden" value="{{ species.id }}" name="species_id">
            <button class="btn btn-danger">Eliminar favorito</button>
        </form>
        {% comment %}
            <button type="button" class="botonVerDetalle verDetalle" name="{{species.id}}" style="float: right; vertical-align:middle"><span>Ver Detalle</span></button>
        {% endcomment %}
    </div>
</div>